// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package pg

import (
	"context"
	"errors"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const saveRefreshTokens = `-- name: SaveRefreshTokens :batchexec
INSERT INTO refresh_tokens (
    id,
    user_id,
    token_hash,
    device_info,
    ip_address,
    expires_at,
    revoked_at,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET
    revoked_at = EXCLUDED.revoked_at
`

type SaveRefreshTokensBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type SaveRefreshTokensParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	DeviceInfo string
	IpAddress  netip.Addr
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
}

func (q *Queries) SaveRefreshTokens(ctx context.Context, arg []SaveRefreshTokensParams) *SaveRefreshTokensBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.UserID,
			a.TokenHash,
			a.DeviceInfo,
			a.IpAddress,
			a.ExpiresAt,
			a.RevokedAt,
			a.CreatedAt,
		}
		batch.Queue(saveRefreshTokens, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &SaveRefreshTokensBatchResults{br, len(arg), false}
}

func (b *SaveRefreshTokensBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *SaveRefreshTokensBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
