// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package pg

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const saveReservations = `-- name: SaveReservations :batchexec

INSERT INTO reservations (
    id,
    space_id,
    user_id,
    date,
    slot,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type SaveReservationsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type SaveReservationsParams struct {
	ID        uuid.UUID
	SpaceID   uuid.UUID
	UserID    uuid.UUID
	Date      time.Time
	Slot      int
	CreatedAt time.Time
}

// ============================================================
// Reservations
// ============================================================
func (q *Queries) SaveReservations(ctx context.Context, arg []SaveReservationsParams) *SaveReservationsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.SpaceID,
			a.UserID,
			a.Date,
			a.Slot,
			a.CreatedAt,
		}
		batch.Queue(saveReservations, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &SaveReservationsBatchResults{br, len(arg), false}
}

func (b *SaveReservationsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *SaveReservationsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
