// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package pg

import (
	"context"
)

// iteratorForSaveWrappedKeys implements pgx.CopyFromSource.
type iteratorForSaveWrappedKeys struct {
	rows                 []SaveWrappedKeysParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveWrappedKeys) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveWrappedKeys) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].UserID,
		r.rows[0].CredentialID,
		r.rows[0].Scope,
		r.rows[0].WrappedDek,
		r.rows[0].WrapAlgorithm,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForSaveWrappedKeys) Err() error {
	return nil
}

func (q *Queries) SaveWrappedKeys(ctx context.Context, arg []SaveWrappedKeysParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"wrapped_keys"}, []string{"id", "user_id", "credential_id", "scope", "wrapped_dek", "wrap_algorithm", "created_at"}, &iteratorForSaveWrappedKeys{rows: arg})
}
