// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pg

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type SpaceType string

const (
	SpaceTypeMeetingRoom SpaceType = "meeting_room"
	SpaceTypeDesk        SpaceType = "desk"
)

func (e *SpaceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SpaceType(s)
	case string:
		*e = SpaceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SpaceType: %T", src)
	}
	return nil
}

type NullSpaceType struct {
	SpaceType SpaceType
	Valid     bool // Valid is true if SpaceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpaceType) Scan(value interface{}) error {
	if value == nil {
		ns.SpaceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SpaceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpaceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SpaceType), nil
}

type UserRole string

const (
	UserRoleMember UserRole = "member"
	UserRoleAdmin  UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Reservation struct {
	ID        uuid.UUID
	SpaceID   uuid.UUID
	UserID    uuid.UUID
	Date      time.Time
	Slot      int
	CreatedAt time.Time
}

type Space struct {
	ID        uuid.UUID
	Name      string
	Type      SpaceType
	Capacity  int
	Active    bool
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Role      UserRole
	CreatedAt time.Time
}
