// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleMember UserRole = "member"
	UserRoleAdmin  UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type WrappedKeyScope string

const (
	WrappedKeyScopeMain  WrappedKeyScope = "main"
	WrappedKeyScopeDecoy WrappedKeyScope = "decoy"
)

func (e *WrappedKeyScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WrappedKeyScope(s)
	case string:
		*e = WrappedKeyScope(s)
	default:
		return fmt.Errorf("unsupported scan type for WrappedKeyScope: %T", src)
	}
	return nil
}

type NullWrappedKeyScope struct {
	WrappedKeyScope WrappedKeyScope
	Valid           bool // Valid is true if WrappedKeyScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWrappedKeyScope) Scan(value interface{}) error {
	if value == nil {
		ns.WrappedKeyScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WrappedKeyScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWrappedKeyScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WrappedKeyScope), nil
}

type Credential struct {
	ID         uuid.UUID
	ExternalID []byte
	UserID     uuid.UUID
	PublicKey  []byte
	SignCount  uint32
	Transports []string
	CreatedAt  time.Time
	RevokedAt  *time.Time
}

type Invite struct {
	ID        uuid.UUID
	CreatedBy uuid.UUID
	CodeHash  string
	UsedBy    uuid.NullUUID
	UsedAt    *time.Time
	ExpiresAt time.Time
	CreatedAt time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	DeviceInfo string
	IpAddress  netip.Addr
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
}

type User struct {
	ID        uuid.UUID
	Role      UserRole
	InvitedBy uuid.NullUUID
	CreatedAt time.Time
}

type WrappedKey struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	CredentialID  uuid.UUID
	Scope         WrappedKeyScope
	WrappedDek    []byte
	WrapAlgorithm string
	CreatedAt     time.Time
}
