// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package pg

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveInvitesByUser = `-- name: CountActiveInvitesByUser :one
SELECT count(*)
FROM invites
WHERE created_by = $1
    AND used_at IS NULL
    AND expires_at > $2
`

type CountActiveInvitesByUserParams struct {
	CreatedBy uuid.UUID
	Now       time.Time
}

func (q *Queries) CountActiveInvitesByUser(ctx context.Context, arg CountActiveInvitesByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveInvitesByUser, arg.CreatedBy, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findCredentialByExternalID = `-- name: FindCredentialByExternalID :one
SELECT id, external_id, user_id, public_key, sign_count, transports, created_at, revoked_at
FROM credentials
WHERE external_id = $1
`

func (q *Queries) FindCredentialByExternalID(ctx context.Context, externalID []byte) (Credential, error) {
	row := q.db.QueryRow(ctx, findCredentialByExternalID, externalID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.UserID,
		&i.PublicKey,
		&i.SignCount,
		&i.Transports,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findCredentialByExternalIDForUpdate = `-- name: FindCredentialByExternalIDForUpdate :one
SELECT id, external_id, user_id, public_key, sign_count, transports, created_at, revoked_at
FROM credentials
WHERE external_id = $1
FOR UPDATE
`

func (q *Queries) FindCredentialByExternalIDForUpdate(ctx context.Context, externalID []byte) (Credential, error) {
	row := q.db.QueryRow(ctx, findCredentialByExternalIDForUpdate, externalID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.UserID,
		&i.PublicKey,
		&i.SignCount,
		&i.Transports,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findInviteByCodeHash = `-- name: FindInviteByCodeHash :one
SELECT id, created_by, code_hash, used_by, used_at, expires_at, created_at
FROM invites
WHERE code_hash = $1
`

func (q *Queries) FindInviteByCodeHash(ctx context.Context, codeHash string) (Invite, error) {
	row := q.db.QueryRow(ctx, findInviteByCodeHash, codeHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CodeHash,
		&i.UsedBy,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findInviteByIDForUpdate = `-- name: FindInviteByIDForUpdate :one
SELECT id, created_by, code_hash, used_by, used_at, expires_at, created_at
FROM invites
WHERE id = $1
FOR UPDATE
`

func (q *Queries) FindInviteByIDForUpdate(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, findInviteByIDForUpdate, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CodeHash,
		&i.UsedBy,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findRefreshTokenByIDForUpdate = `-- name: FindRefreshTokenByIDForUpdate :one
SELECT id, user_id, token_hash, device_info, ip_address, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE id = $1
FOR UPDATE
`

func (q *Queries) FindRefreshTokenByIDForUpdate(ctx context.Context, id uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshTokenByIDForUpdate, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findRefreshTokenByTokenHash = `-- name: FindRefreshTokenByTokenHash :one
SELECT id, user_id, token_hash, device_info, ip_address, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) FindRefreshTokenByTokenHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshTokenByTokenHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findRefreshTokenByTokenHashForUpdate = `-- name: FindRefreshTokenByTokenHashForUpdate :one
SELECT id, user_id, token_hash, device_info, ip_address, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) FindRefreshTokenByTokenHashForUpdate(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshTokenByTokenHashForUpdate, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findRootUser = `-- name: FindRootUser :one
SELECT id, role, invited_by, created_at FROM users WHERE invited_by IS NULL LIMIT 1
`

func (q *Queries) FindRootUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, findRootUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, role, invited_by, created_at FROM users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveRefreshTokensByUserIDs = `-- name: ListActiveRefreshTokensByUserIDs :many
SELECT id, user_id, token_hash, device_info, ip_address, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE user_id = ANY($1::uuid[])
    AND revoked_at IS NULL
    AND expires_at > $2
`

type ListActiveRefreshTokensByUserIDsParams struct {
	UserIds []uuid.UUID
	Now     time.Time
}

func (q *Queries) ListActiveRefreshTokensByUserIDs(ctx context.Context, arg ListActiveRefreshTokensByUserIDsParams) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listActiveRefreshTokensByUserIDs, arg.UserIds, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByUserID = `-- name: ListCredentialsByUserID :many
SELECT id, external_id, user_id, public_key, sign_count, transports, created_at, revoked_at
FROM credentials
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListCredentialsByUserID(ctx context.Context, userID uuid.UUID) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.UserID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDescendantUserIDs = `-- name: ListDescendantUserIDs :many
WITH RECURSIVE compromised_chain AS (
    SELECT users.id
    FROM users
    WHERE users.id = $1

    UNION ALL

    SELECT u.id
    FROM users u
    JOIN compromised_chain cc
        ON u.invited_by = cc.id
)
SELECT cc.id
FROM compromised_chain cc
`

func (q *Queries) ListDescendantUserIDs(ctx context.Context, root uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDescendantUserIDs, root)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWrappedKeysByCredentialID = `-- name: ListWrappedKeysByCredentialID :many
SELECT id, user_id, credential_id, scope, wrapped_dek, wrap_algorithm, created_at
FROM wrapped_keys
WHERE credential_id = $1
`

func (q *Queries) ListWrappedKeysByCredentialID(ctx context.Context, credentialID uuid.UUID) ([]WrappedKey, error) {
	rows, err := q.db.Query(ctx, listWrappedKeysByCredentialID, credentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WrappedKey
	for rows.Next() {
		var i WrappedKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.Scope,
			&i.WrappedDek,
			&i.WrapAlgorithm,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserByID = `-- name: LockUserByID :exec
SELECT pg_advisory_xact_lock(
    hashtextextended($1::text, 0)
)
`

func (q *Queries) LockUserByID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, lockUserByID, userID)
	return err
}

const saveCredential = `-- name: SaveCredential :exec
INSERT INTO credentials (
    id,
    external_id,
    user_id,
    public_key,
    sign_count,
    transports,
    created_at,
    revoked_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (id) DO UPDATE
SET
    sign_count = EXCLUDED.sign_count,
    revoked_at = EXCLUDED.revoked_at
`

type SaveCredentialParams struct {
	ID         uuid.UUID
	ExternalID []byte
	UserID     uuid.UUID
	PublicKey  []byte
	SignCount  uint32
	Transports []string
	CreatedAt  time.Time
	RevokedAt  *time.Time
}

func (q *Queries) SaveCredential(ctx context.Context, arg SaveCredentialParams) error {
	_, err := q.db.Exec(ctx, saveCredential,
		arg.ID,
		arg.ExternalID,
		arg.UserID,
		arg.PublicKey,
		arg.SignCount,
		arg.Transports,
		arg.CreatedAt,
		arg.RevokedAt,
	)
	return err
}

const saveInvite = `-- name: SaveInvite :exec
INSERT INTO invites (
    id,
    created_by,
    code_hash,
    used_by,
    used_at,
    expires_at,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (id) DO UPDATE
SET
    used_by = EXCLUDED.used_by,
    used_at = EXCLUDED.used_at
`

type SaveInviteParams struct {
	ID        uuid.UUID
	CreatedBy uuid.UUID
	CodeHash  string
	UsedBy    uuid.NullUUID
	UsedAt    *time.Time
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) SaveInvite(ctx context.Context, arg SaveInviteParams) error {
	_, err := q.db.Exec(ctx, saveInvite,
		arg.ID,
		arg.CreatedBy,
		arg.CodeHash,
		arg.UsedBy,
		arg.UsedAt,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const saveUser = `-- name: SaveUser :exec
INSERT INTO users (
    id,
    role,
    invited_by,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type SaveUserParams struct {
	ID        uuid.UUID
	Role      UserRole
	InvitedBy uuid.NullUUID
	CreatedAt time.Time
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) error {
	_, err := q.db.Exec(ctx, saveUser,
		arg.ID,
		arg.Role,
		arg.InvitedBy,
		arg.CreatedAt,
	)
	return err
}

type SaveWrappedKeysParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	CredentialID  uuid.UUID
	Scope         WrappedKeyScope
	WrappedDek    []byte
	WrapAlgorithm string
	CreatedAt     time.Time
}
