// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package pg

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one

SELECT count(*)::bigint
FROM users
`

// ============================================================
// Users
// ============================================================
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteReservationsByIDs = `-- name: DeleteReservationsByIDs :exec
DELETE FROM reservations
WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteReservationsByIDs(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReservationsByIDs, ids)
	return err
}

const deleteReservationsByUserID = `-- name: DeleteReservationsByUserID :exec
DELETE FROM reservations
WHERE user_id = $1
`

func (q *Queries) DeleteReservationsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReservationsByUserID, userID)
	return err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces
WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findReservationByID = `-- name: FindReservationByID :one
SELECT id, space_id, user_id, date, slot, created_at
FROM reservations
WHERE id = $1
`

func (q *Queries) FindReservationByID(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, findReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Date,
		&i.Slot,
		&i.CreatedAt,
	)
	return i, err
}

const findReservationByIDForUpdate = `-- name: FindReservationByIDForUpdate :one
SELECT id, space_id, user_id, date, slot, created_at
FROM reservations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) FindReservationByIDForUpdate(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, findReservationByIDForUpdate, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Date,
		&i.Slot,
		&i.CreatedAt,
	)
	return i, err
}

const findSpaceByID = `-- name: FindSpaceByID :one
SELECT id, name, type, capacity, active, created_at
FROM spaces
WHERE id = $1
`

func (q *Queries) FindSpaceByID(ctx context.Context, id uuid.UUID) (Space, error) {
	row := q.db.QueryRow(ctx, findSpaceByID, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Capacity,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const findSpaceByIDForUpdate = `-- name: FindSpaceByIDForUpdate :one
SELECT id, name, type, capacity, active, created_at
FROM spaces
WHERE id = $1
FOR UPDATE
`

func (q *Queries) FindSpaceByIDForUpdate(ctx context.Context, id uuid.UUID) (Space, error) {
	row := q.db.QueryRow(ctx, findSpaceByIDForUpdate, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Capacity,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, role, created_at
FROM users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Role, &i.CreatedAt)
	return i, err
}

const findUserByIDForUpdate = `-- name: FindUserByIDForUpdate :one
SELECT id, role, created_at
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) FindUserByIDForUpdate(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByIDForUpdate, id)
	var i User
	err := row.Scan(&i.ID, &i.Role, &i.CreatedAt)
	return i, err
}

const hasReservationConflict = `-- name: HasReservationConflict :one
SELECT EXISTS (
    SELECT 1
    FROM reservations
    WHERE space_id = $1
      AND date = $2
      AND slot = ANY($3::smallint[])
) AS conflict
`

type HasReservationConflictParams struct {
	SpaceID uuid.UUID
	Date    time.Time
	Slots   []int
}

func (q *Queries) HasReservationConflict(ctx context.Context, arg HasReservationConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasReservationConflict, arg.SpaceID, arg.Date, arg.Slots)
	var conflict bool
	err := row.Scan(&conflict)
	return conflict, err
}

const listReservationsBySpaceAndDate = `-- name: ListReservationsBySpaceAndDate :many
SELECT id, space_id, user_id, date, slot, created_at
FROM reservations
WHERE space_id = $1
  AND date = $2
ORDER BY slot
`

type ListReservationsBySpaceAndDateParams struct {
	SpaceID uuid.UUID
	Date    time.Time
}

func (q *Queries) ListReservationsBySpaceAndDate(ctx context.Context, arg ListReservationsBySpaceAndDateParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsBySpaceAndDate, arg.SpaceID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.UserID,
			&i.Date,
			&i.Slot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByUserID = `-- name: ListReservationsByUserID :many
SELECT id, space_id, user_id, date, slot, created_at
FROM reservations
WHERE user_id = $1
ORDER BY date, space_id, slot
`

func (q *Queries) ListReservationsByUserID(ctx context.Context, userID uuid.UUID) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.UserID,
			&i.Date,
			&i.Slot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, name, type, capacity, active, created_at
FROM spaces
WHERE
    NOT $1::boolean
    OR active
ORDER BY name, id
`

func (q *Queries) ListSpaces(ctx context.Context, onlyActive bool) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpaces, onlyActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Capacity,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, role, created_at
FROM users
ORDER BY created_at, id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Role, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRootCreation = `-- name: LockRootCreation :exec
SELECT pg_advisory_xact_lock(
    hashtextextended('slotify:create-root-user', 0)
)
`

func (q *Queries) LockRootCreation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockRootCreation)
	return err
}

const saveSpace = `-- name: SaveSpace :exec

INSERT INTO spaces (
    id,
    name,
    type,
    capacity,
    active,
    created_at
)
VALUES (
    $1,
    $2,
    $3::space_type,
    $4,
    $5,
    $6
)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    type = EXCLUDED.type,
    capacity = EXCLUDED.capacity,
    active = EXCLUDED.active
`

type SaveSpaceParams struct {
	ID        uuid.UUID
	Name      string
	Type      SpaceType
	Capacity  int
	Active    bool
	CreatedAt time.Time
}

// ============================================================
// Spaces
// ============================================================
func (q *Queries) SaveSpace(ctx context.Context, arg SaveSpaceParams) error {
	_, err := q.db.Exec(ctx, saveSpace,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Capacity,
		arg.Active,
		arg.CreatedAt,
	)
	return err
}

const saveUser = `-- name: SaveUser :exec
INSERT INTO users (
    id,
    role,
    created_at
)
VALUES (
    $1,
    $2::user_role,
    $3
)
ON CONFLICT (id) DO UPDATE
SET
    role = EXCLUDED.role
`

type SaveUserParams struct {
	ID        uuid.UUID
	Role      UserRole
	CreatedAt time.Time
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) error {
	_, err := q.db.Exec(ctx, saveUser, arg.ID, arg.Role, arg.CreatedAt)
	return err
}
