// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelBookingOperation   OperationName = "CancelBooking"
	CreateBookingOperation   OperationName = "CreateBooking"
	CreateSpaceOperation     OperationName = "CreateSpace"
	CreateUserOperation      OperationName = "CreateUser"
	DeactivateSpaceOperation OperationName = "DeactivateSpace"
	DeleteSpaceOperation     OperationName = "DeleteSpace"
	DeleteUserOperation      OperationName = "DeleteUser"
	GetOccupancyOperation    OperationName = "GetOccupancy"
	GetReservationOperation  OperationName = "GetReservation"
	GetSpaceOperation        OperationName = "GetSpace"
	GetUserOperation         OperationName = "GetUser"
	HealthCheckOperation     OperationName = "HealthCheck"
	ListMyBookingsOperation  OperationName = "ListMyBookings"
	ListSpacesOperation      OperationName = "ListSpaces"
	ListUsersOperation       OperationName = "ListUsers"
	UpdateSpaceOperation     OperationName = "UpdateSpace"
	UpdateUserRoleOperation  OperationName = "UpdateUserRole"
)
