// Code generated by ogen, DO NOT EDIT.
package api

type CancelBookingRes interface {
	cancelBookingRes()
}

type CreateBookingRes interface {
	createBookingRes()
}

type CreateSpaceRes interface {
	createSpaceRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeactivateSpaceRes interface {
	deactivateSpaceRes()
}

type DeleteSpaceRes interface {
	deleteSpaceRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type GetOccupancyRes interface {
	getOccupancyRes()
}

type GetReservationRes interface {
	getReservationRes()
}

type GetSpaceRes interface {
	getSpaceRes()
}

type GetUserRes interface {
	getUserRes()
}

type ListMyBookingsRes interface {
	listMyBookingsRes()
}

type ListSpacesRes interface {
	listSpacesRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type UpdateSpaceRes interface {
	updateSpaceRes()
}

type UpdateUserRoleRes interface {
	updateUserRoleRes()
}
