// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelBooking implements cancelBooking operation.
	//
	// Отменить бронь (владелец или admin).
	//
	// POST /bookings/cancel
	CancelBooking(ctx context.Context, req *CancelBookingRequest) (CancelBookingRes, error)
	// CreateBooking implements createBooking operation.
	//
	// Пользователь берётся из токена, а не из тела запроса.
	//
	// POST /bookings
	CreateBooking(ctx context.Context, req *CreateBookingRequest) (CreateBookingRes, error)
	// CreateSpace implements createSpace operation.
	//
	// Создать пространство (admin).
	//
	// POST /spaces
	CreateSpace(ctx context.Context, req *CreateSpaceRequest) (CreateSpaceRes, error)
	// CreateUser implements createUser operation.
	//
	// Создать пользователя.
	//
	// POST /users
	CreateUser(ctx context.Context, req *CreateUserRequest) (CreateUserRes, error)
	// DeactivateSpace implements deactivateSpace operation.
	//
	// Деактивировать пространство (admin).
	//
	// POST /spaces/{id}/deactivate
	DeactivateSpace(ctx context.Context, params DeactivateSpaceParams) (DeactivateSpaceRes, error)
	// DeleteSpace implements deleteSpace operation.
	//
	// Удалить пространство (admin).
	//
	// DELETE /spaces/{id}
	DeleteSpace(ctx context.Context, params DeleteSpaceParams) (DeleteSpaceRes, error)
	// DeleteUser implements deleteUser operation.
	//
	// Удалить пользователя (admin).
	//
	// DELETE /users/{id}
	DeleteUser(ctx context.Context, params DeleteUserParams) (DeleteUserRes, error)
	// GetOccupancy implements getOccupancy operation.
	//
	// Занятые слоты пространства за день.
	//
	// GET /bookings/occupancy
	GetOccupancy(ctx context.Context, params GetOccupancyParams) (GetOccupancyRes, error)
	// GetReservation implements getReservation operation.
	//
	// Получить один слот-бронь по ID.
	//
	// GET /bookings/{id}
	GetReservation(ctx context.Context, params GetReservationParams) (GetReservationRes, error)
	// GetSpace implements getSpace operation.
	//
	// Получить пространство.
	//
	// GET /spaces/{id}
	GetSpace(ctx context.Context, params GetSpaceParams) (GetSpaceRes, error)
	// GetUser implements getUser operation.
	//
	// Получить пользователя.
	//
	// GET /users/{id}
	GetUser(ctx context.Context, params GetUserParams) (GetUserRes, error)
	// HealthCheck implements healthCheck operation.
	//
	// Проверка живости.
	//
	// GET /healthz
	HealthCheck(ctx context.Context) error
	// ListMyBookings implements listMyBookings operation.
	//
	// Мои брони (слоты сгруппированы в диапазоны).
	//
	// GET /bookings/my
	ListMyBookings(ctx context.Context) (ListMyBookingsRes, error)
	// ListSpaces implements listSpaces operation.
	//
	// Список пространств.
	//
	// GET /spaces
	ListSpaces(ctx context.Context, params ListSpacesParams) (ListSpacesRes, error)
	// ListUsers implements listUsers operation.
	//
	// Список пользователей (admin).
	//
	// GET /users
	ListUsers(ctx context.Context) (ListUsersRes, error)
	// UpdateSpace implements updateSpace operation.
	//
	// Изменить имя / вместимость (admin).
	//
	// PATCH /spaces/{id}
	UpdateSpace(ctx context.Context, req *UpdateSpaceRequest, params UpdateSpaceParams) (UpdateSpaceRes, error)
	// UpdateUserRole implements updateUserRole operation.
	//
	// Сменить роль (admin).
	//
	// PATCH /users/{id}/role
	UpdateUserRole(ctx context.Context, req *UpdateRoleRequest, params UpdateUserRoleParams) (UpdateUserRoleRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
