// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelBooking implements cancelBooking operation.
//
// Отменить бронь (владелец или admin).
//
// POST /bookings/cancel
func (UnimplementedHandler) CancelBooking(ctx context.Context, req *CancelBookingRequest) (r CancelBookingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateBooking implements createBooking operation.
//
// Пользователь берётся из токена, а не из тела запроса.
//
// POST /bookings
func (UnimplementedHandler) CreateBooking(ctx context.Context, req *CreateBookingRequest) (r CreateBookingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSpace implements createSpace operation.
//
// Создать пространство (admin).
//
// POST /spaces
func (UnimplementedHandler) CreateSpace(ctx context.Context, req *CreateSpaceRequest) (r CreateSpaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements createUser operation.
//
// Создать пользователя.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *CreateUserRequest) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeactivateSpace implements deactivateSpace operation.
//
// Деактивировать пространство (admin).
//
// POST /spaces/{id}/deactivate
func (UnimplementedHandler) DeactivateSpace(ctx context.Context, params DeactivateSpaceParams) (r DeactivateSpaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSpace implements deleteSpace operation.
//
// Удалить пространство (admin).
//
// DELETE /spaces/{id}
func (UnimplementedHandler) DeleteSpace(ctx context.Context, params DeleteSpaceParams) (r DeleteSpaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUser implements deleteUser operation.
//
// Удалить пользователя (admin).
//
// DELETE /users/{id}
func (UnimplementedHandler) DeleteUser(ctx context.Context, params DeleteUserParams) (r DeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOccupancy implements getOccupancy operation.
//
// Занятые слоты пространства за день.
//
// GET /bookings/occupancy
func (UnimplementedHandler) GetOccupancy(ctx context.Context, params GetOccupancyParams) (r GetOccupancyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetReservation implements getReservation operation.
//
// Получить один слот-бронь по ID.
//
// GET /bookings/{id}
func (UnimplementedHandler) GetReservation(ctx context.Context, params GetReservationParams) (r GetReservationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpace implements getSpace operation.
//
// Получить пространство.
//
// GET /spaces/{id}
func (UnimplementedHandler) GetSpace(ctx context.Context, params GetSpaceParams) (r GetSpaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements getUser operation.
//
// Получить пользователя.
//
// GET /users/{id}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r GetUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthCheck implements healthCheck operation.
//
// Проверка живости.
//
// GET /healthz
func (UnimplementedHandler) HealthCheck(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// ListMyBookings implements listMyBookings operation.
//
// Мои брони (слоты сгруппированы в диапазоны).
//
// GET /bookings/my
func (UnimplementedHandler) ListMyBookings(ctx context.Context) (r ListMyBookingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSpaces implements listSpaces operation.
//
// Список пространств.
//
// GET /spaces
func (UnimplementedHandler) ListSpaces(ctx context.Context, params ListSpacesParams) (r ListSpacesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements listUsers operation.
//
// Список пользователей (admin).
//
// GET /users
func (UnimplementedHandler) ListUsers(ctx context.Context) (r ListUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSpace implements updateSpace operation.
//
// Изменить имя / вместимость (admin).
//
// PATCH /spaces/{id}
func (UnimplementedHandler) UpdateSpace(ctx context.Context, req *UpdateSpaceRequest, params UpdateSpaceParams) (r UpdateSpaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserRole implements updateUserRole operation.
//
// Сменить роль (admin).
//
// PATCH /users/{id}/role
func (UnimplementedHandler) UpdateUserRole(ctx context.Context, req *UpdateRoleRequest, params UpdateUserRoleParams) (r UpdateUserRoleRes, _ error) {
	return r, ht.ErrNotImplemented
}
