// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/Booking
type Booking struct {
	SpaceID        uuid.UUID   `json:"space_id"`
	Date           time.Time   `json:"date"`
	StartSlot      Slot        `json:"start_slot"`
	EndSlot        Slot        `json:"end_slot"`
	ReservationIds []uuid.UUID `json:"reservation_ids"`
}

// GetSpaceID returns the value of SpaceID.
func (s *Booking) GetSpaceID() uuid.UUID {
	return s.SpaceID
}

// GetDate returns the value of Date.
func (s *Booking) GetDate() time.Time {
	return s.Date
}

// GetStartSlot returns the value of StartSlot.
func (s *Booking) GetStartSlot() Slot {
	return s.StartSlot
}

// GetEndSlot returns the value of EndSlot.
func (s *Booking) GetEndSlot() Slot {
	return s.EndSlot
}

// GetReservationIds returns the value of ReservationIds.
func (s *Booking) GetReservationIds() []uuid.UUID {
	return s.ReservationIds
}

// SetSpaceID sets the value of SpaceID.
func (s *Booking) SetSpaceID(val uuid.UUID) {
	s.SpaceID = val
}

// SetDate sets the value of Date.
func (s *Booking) SetDate(val time.Time) {
	s.Date = val
}

// SetStartSlot sets the value of StartSlot.
func (s *Booking) SetStartSlot(val Slot) {
	s.StartSlot = val
}

// SetEndSlot sets the value of EndSlot.
func (s *Booking) SetEndSlot(val Slot) {
	s.EndSlot = val
}

// SetReservationIds sets the value of ReservationIds.
func (s *Booking) SetReservationIds(val []uuid.UUID) {
	s.ReservationIds = val
}

func (*Booking) createBookingRes() {}

type CancelBookingBadRequest Error

func (*CancelBookingBadRequest) cancelBookingRes() {}

type CancelBookingForbidden Error

func (*CancelBookingForbidden) cancelBookingRes() {}

// CancelBookingNoContent is response for CancelBooking operation.
type CancelBookingNoContent struct{}

func (*CancelBookingNoContent) cancelBookingRes() {}

type CancelBookingNotFound Error

func (*CancelBookingNotFound) cancelBookingRes() {}

// Ref: #/components/schemas/CancelBookingRequest
type CancelBookingRequest struct {
	ReservationIds []uuid.UUID `json:"reservation_ids"`
}

// GetReservationIds returns the value of ReservationIds.
func (s *CancelBookingRequest) GetReservationIds() []uuid.UUID {
	return s.ReservationIds
}

// SetReservationIds sets the value of ReservationIds.
func (s *CancelBookingRequest) SetReservationIds(val []uuid.UUID) {
	s.ReservationIds = val
}

type CancelBookingUnauthorized Error

func (*CancelBookingUnauthorized) cancelBookingRes() {}

type CreateBookingBadRequest Error

func (*CreateBookingBadRequest) createBookingRes() {}

type CreateBookingConflict Error

func (*CreateBookingConflict) createBookingRes() {}

type CreateBookingNotFound Error

func (*CreateBookingNotFound) createBookingRes() {}

// Ref: #/components/schemas/CreateBookingRequest
type CreateBookingRequest struct {
	SpaceID uuid.UUID `json:"space_id"`
	// Дата в формате YYYY-MM-DD (UTC).
	Date      time.Time `json:"date"`
	StartSlot Slot      `json:"start_slot"`
	EndSlot   Slot      `json:"end_slot"`
	People    OptInt    `json:"people"`
}

// GetSpaceID returns the value of SpaceID.
func (s *CreateBookingRequest) GetSpaceID() uuid.UUID {
	return s.SpaceID
}

// GetDate returns the value of Date.
func (s *CreateBookingRequest) GetDate() time.Time {
	return s.Date
}

// GetStartSlot returns the value of StartSlot.
func (s *CreateBookingRequest) GetStartSlot() Slot {
	return s.StartSlot
}

// GetEndSlot returns the value of EndSlot.
func (s *CreateBookingRequest) GetEndSlot() Slot {
	return s.EndSlot
}

// GetPeople returns the value of People.
func (s *CreateBookingRequest) GetPeople() OptInt {
	return s.People
}

// SetSpaceID sets the value of SpaceID.
func (s *CreateBookingRequest) SetSpaceID(val uuid.UUID) {
	s.SpaceID = val
}

// SetDate sets the value of Date.
func (s *CreateBookingRequest) SetDate(val time.Time) {
	s.Date = val
}

// SetStartSlot sets the value of StartSlot.
func (s *CreateBookingRequest) SetStartSlot(val Slot) {
	s.StartSlot = val
}

// SetEndSlot sets the value of EndSlot.
func (s *CreateBookingRequest) SetEndSlot(val Slot) {
	s.EndSlot = val
}

// SetPeople sets the value of People.
func (s *CreateBookingRequest) SetPeople(val OptInt) {
	s.People = val
}

type CreateBookingUnauthorized Error

func (*CreateBookingUnauthorized) createBookingRes() {}

type CreateBookingUnprocessableEntity Error

func (*CreateBookingUnprocessableEntity) createBookingRes() {}

type CreateSpaceBadRequest Error

func (*CreateSpaceBadRequest) createSpaceRes() {}

type CreateSpaceForbidden Error

func (*CreateSpaceForbidden) createSpaceRes() {}

// Ref: #/components/schemas/CreateSpaceRequest
type CreateSpaceRequest struct {
	Name     string    `json:"name"`
	Type     SpaceType `json:"type"`
	Capacity int       `json:"capacity"`
}

// GetName returns the value of Name.
func (s *CreateSpaceRequest) GetName() string {
	return s.Name
}

// GetType returns the value of Type.
func (s *CreateSpaceRequest) GetType() SpaceType {
	return s.Type
}

// GetCapacity returns the value of Capacity.
func (s *CreateSpaceRequest) GetCapacity() int {
	return s.Capacity
}

// SetName sets the value of Name.
func (s *CreateSpaceRequest) SetName(val string) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *CreateSpaceRequest) SetType(val SpaceType) {
	s.Type = val
}

// SetCapacity sets the value of Capacity.
func (s *CreateSpaceRequest) SetCapacity(val int) {
	s.Capacity = val
}

type CreateSpaceUnauthorized Error

func (*CreateSpaceUnauthorized) createSpaceRes() {}

type CreateUserBadRequest Error

func (*CreateUserBadRequest) createUserRes() {}

type CreateUserForbidden Error

func (*CreateUserForbidden) createUserRes() {}

// Ref: #/components/schemas/CreateUserRequest
type CreateUserRequest struct {
	Role Role `json:"role"`
}

// GetRole returns the value of Role.
func (s *CreateUserRequest) GetRole() Role {
	return s.Role
}

// SetRole sets the value of Role.
func (s *CreateUserRequest) SetRole(val Role) {
	s.Role = val
}

type CreateUserUnauthorized Error

func (*CreateUserUnauthorized) createUserRes() {}

type DeactivateSpaceConflict Error

func (*DeactivateSpaceConflict) deactivateSpaceRes() {}

type DeactivateSpaceForbidden Error

func (*DeactivateSpaceForbidden) deactivateSpaceRes() {}

// DeactivateSpaceNoContent is response for DeactivateSpace operation.
type DeactivateSpaceNoContent struct{}

func (*DeactivateSpaceNoContent) deactivateSpaceRes() {}

type DeactivateSpaceNotFound Error

func (*DeactivateSpaceNotFound) deactivateSpaceRes() {}

type DeactivateSpaceUnauthorized Error

func (*DeactivateSpaceUnauthorized) deactivateSpaceRes() {}

type DeleteSpaceConflict Error

func (*DeleteSpaceConflict) deleteSpaceRes() {}

type DeleteSpaceForbidden Error

func (*DeleteSpaceForbidden) deleteSpaceRes() {}

// DeleteSpaceNoContent is response for DeleteSpace operation.
type DeleteSpaceNoContent struct{}

func (*DeleteSpaceNoContent) deleteSpaceRes() {}

type DeleteSpaceNotFound Error

func (*DeleteSpaceNotFound) deleteSpaceRes() {}

type DeleteSpaceUnauthorized Error

func (*DeleteSpaceUnauthorized) deleteSpaceRes() {}

type DeleteUserConflict Error

func (*DeleteUserConflict) deleteUserRes() {}

type DeleteUserForbidden Error

func (*DeleteUserForbidden) deleteUserRes() {}

// DeleteUserNoContent is response for DeleteUser operation.
type DeleteUserNoContent struct{}

func (*DeleteUserNoContent) deleteUserRes() {}

type DeleteUserNotFound Error

func (*DeleteUserNotFound) deleteUserRes() {}

type DeleteUserUnauthorized Error

func (*DeleteUserUnauthorized) deleteUserRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

func (*Error) listMyBookingsRes() {}
func (*Error) listSpacesRes()     {}

type GetOccupancyBadRequest Error

func (*GetOccupancyBadRequest) getOccupancyRes() {}

type GetOccupancyUnauthorized Error

func (*GetOccupancyUnauthorized) getOccupancyRes() {}

type GetReservationNotFound Error

func (*GetReservationNotFound) getReservationRes() {}

type GetReservationUnauthorized Error

func (*GetReservationUnauthorized) getReservationRes() {}

type GetSpaceNotFound Error

func (*GetSpaceNotFound) getSpaceRes() {}

type GetSpaceUnauthorized Error

func (*GetSpaceUnauthorized) getSpaceRes() {}

type GetUserNotFound Error

func (*GetUserNotFound) getUserRes() {}

type GetUserUnauthorized Error

func (*GetUserUnauthorized) getUserRes() {}

// HealthCheckOK is response for HealthCheck operation.
type HealthCheckOK struct{}

type ListMyBookingsOKApplicationJSON []Booking

func (*ListMyBookingsOKApplicationJSON) listMyBookingsRes() {}

type ListSpacesOKApplicationJSON []Space

func (*ListSpacesOKApplicationJSON) listSpacesRes() {}

type ListUsersForbidden Error

func (*ListUsersForbidden) listUsersRes() {}

type ListUsersOKApplicationJSON []User

func (*ListUsersOKApplicationJSON) listUsersRes() {}

type ListUsersUnauthorized Error

func (*ListUsersUnauthorized) listUsersRes() {}

// Ref: #/components/schemas/Occupancy
type Occupancy struct {
	SpaceID  uuid.UUID       `json:"space_id"`
	Date     time.Time       `json:"date"`
	Occupied []SlotOccupancy `json:"occupied"`
}

// GetSpaceID returns the value of SpaceID.
func (s *Occupancy) GetSpaceID() uuid.UUID {
	return s.SpaceID
}

// GetDate returns the value of Date.
func (s *Occupancy) GetDate() time.Time {
	return s.Date
}

// GetOccupied returns the value of Occupied.
func (s *Occupancy) GetOccupied() []SlotOccupancy {
	return s.Occupied
}

// SetSpaceID sets the value of SpaceID.
func (s *Occupancy) SetSpaceID(val uuid.UUID) {
	s.SpaceID = val
}

// SetDate sets the value of Date.
func (s *Occupancy) SetDate(val time.Time) {
	s.Date = val
}

// SetOccupied sets the value of Occupied.
func (s *Occupancy) SetOccupied(val []SlotOccupancy) {
	s.Occupied = val
}

func (*Occupancy) getOccupancyRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Reservation
type Reservation struct {
	ID        uuid.UUID `json:"id"`
	SpaceID   uuid.UUID `json:"space_id"`
	UserID    uuid.UUID `json:"user_id"`
	Date      time.Time `json:"date"`
	Slot      Slot      `json:"slot"`
	CreatedAt time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Reservation) GetID() uuid.UUID {
	return s.ID
}

// GetSpaceID returns the value of SpaceID.
func (s *Reservation) GetSpaceID() uuid.UUID {
	return s.SpaceID
}

// GetUserID returns the value of UserID.
func (s *Reservation) GetUserID() uuid.UUID {
	return s.UserID
}

// GetDate returns the value of Date.
func (s *Reservation) GetDate() time.Time {
	return s.Date
}

// GetSlot returns the value of Slot.
func (s *Reservation) GetSlot() Slot {
	return s.Slot
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Reservation) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Reservation) SetID(val uuid.UUID) {
	s.ID = val
}

// SetSpaceID sets the value of SpaceID.
func (s *Reservation) SetSpaceID(val uuid.UUID) {
	s.SpaceID = val
}

// SetUserID sets the value of UserID.
func (s *Reservation) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetDate sets the value of Date.
func (s *Reservation) SetDate(val time.Time) {
	s.Date = val
}

// SetSlot sets the value of Slot.
func (s *Reservation) SetSlot(val Slot) {
	s.Slot = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Reservation) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*Reservation) getReservationRes() {}

// Ref: #/components/schemas/Role
type Role string

const (
	RoleMember Role = "member"
	RoleAdmin  Role = "admin"
)

// AllValues returns all Role values.
func (Role) AllValues() []Role {
	return []Role{
		RoleMember,
		RoleAdmin,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Role) MarshalText() ([]byte, error) {
	switch s {
	case RoleMember:
		return []byte(s), nil
	case RoleAdmin:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Role) UnmarshalText(data []byte) error {
	switch Role(data) {
	case RoleMember:
		*s = RoleMember
		return nil
	case RoleAdmin:
		*s = RoleAdmin
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type Slot int

// Ref: #/components/schemas/SlotOccupancy
type SlotOccupancy struct {
	Slot   Slot      `json:"slot"`
	UserID uuid.UUID `json:"user_id"`
}

// GetSlot returns the value of Slot.
func (s *SlotOccupancy) GetSlot() Slot {
	return s.Slot
}

// GetUserID returns the value of UserID.
func (s *SlotOccupancy) GetUserID() uuid.UUID {
	return s.UserID
}

// SetSlot sets the value of Slot.
func (s *SlotOccupancy) SetSlot(val Slot) {
	s.Slot = val
}

// SetUserID sets the value of UserID.
func (s *SlotOccupancy) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// Ref: #/components/schemas/Space
type Space struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Type      SpaceType `json:"type"`
	Capacity  int       `json:"capacity"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Space) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Space) GetName() string {
	return s.Name
}

// GetType returns the value of Type.
func (s *Space) GetType() SpaceType {
	return s.Type
}

// GetCapacity returns the value of Capacity.
func (s *Space) GetCapacity() int {
	return s.Capacity
}

// GetActive returns the value of Active.
func (s *Space) GetActive() bool {
	return s.Active
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Space) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Space) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Space) SetName(val string) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *Space) SetType(val SpaceType) {
	s.Type = val
}

// SetCapacity sets the value of Capacity.
func (s *Space) SetCapacity(val int) {
	s.Capacity = val
}

// SetActive sets the value of Active.
func (s *Space) SetActive(val bool) {
	s.Active = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Space) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*Space) createSpaceRes() {}
func (*Space) getSpaceRes()    {}
func (*Space) updateSpaceRes() {}

// Ref: #/components/schemas/SpaceType
type SpaceType string

const (
	SpaceTypeMeetingRoom SpaceType = "meeting_room"
	SpaceTypeDesk        SpaceType = "desk"
)

// AllValues returns all SpaceType values.
func (SpaceType) AllValues() []SpaceType {
	return []SpaceType{
		SpaceTypeMeetingRoom,
		SpaceTypeDesk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SpaceType) MarshalText() ([]byte, error) {
	switch s {
	case SpaceTypeMeetingRoom:
		return []byte(s), nil
	case SpaceTypeDesk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SpaceType) UnmarshalText(data []byte) error {
	switch SpaceType(data) {
	case SpaceTypeMeetingRoom:
		*s = SpaceTypeMeetingRoom
		return nil
	case SpaceTypeDesk:
		*s = SpaceTypeDesk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/UpdateRoleRequest
type UpdateRoleRequest struct {
	Role Role `json:"role"`
}

// GetRole returns the value of Role.
func (s *UpdateRoleRequest) GetRole() Role {
	return s.Role
}

// SetRole sets the value of Role.
func (s *UpdateRoleRequest) SetRole(val Role) {
	s.Role = val
}

type UpdateSpaceBadRequest Error

func (*UpdateSpaceBadRequest) updateSpaceRes() {}

type UpdateSpaceForbidden Error

func (*UpdateSpaceForbidden) updateSpaceRes() {}

type UpdateSpaceNotFound Error

func (*UpdateSpaceNotFound) updateSpaceRes() {}

// Ref: #/components/schemas/UpdateSpaceRequest
type UpdateSpaceRequest struct {
	Name     OptString `json:"name"`
	Capacity OptInt    `json:"capacity"`
}

// GetName returns the value of Name.
func (s *UpdateSpaceRequest) GetName() OptString {
	return s.Name
}

// GetCapacity returns the value of Capacity.
func (s *UpdateSpaceRequest) GetCapacity() OptInt {
	return s.Capacity
}

// SetName sets the value of Name.
func (s *UpdateSpaceRequest) SetName(val OptString) {
	s.Name = val
}

// SetCapacity sets the value of Capacity.
func (s *UpdateSpaceRequest) SetCapacity(val OptInt) {
	s.Capacity = val
}

type UpdateSpaceUnauthorized Error

func (*UpdateSpaceUnauthorized) updateSpaceRes() {}

type UpdateUserRoleBadRequest Error

func (*UpdateUserRoleBadRequest) updateUserRoleRes() {}

type UpdateUserRoleForbidden Error

func (*UpdateUserRoleForbidden) updateUserRoleRes() {}

type UpdateUserRoleNotFound Error

func (*UpdateUserRoleNotFound) updateUserRoleRes() {}

type UpdateUserRoleUnauthorized Error

func (*UpdateUserRoleUnauthorized) updateUserRoleRes() {}

// Ref: #/components/schemas/User
type User struct {
	ID        uuid.UUID `json:"id"`
	Role      Role      `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	// PASETO v4 local token.
	Token string `json:"token"`
}

// GetID returns the value of ID.
func (s *User) GetID() uuid.UUID {
	return s.ID
}

// GetRole returns the value of Role.
func (s *User) GetRole() Role {
	return s.Role
}

// GetCreatedAt returns the value of CreatedAt.
func (s *User) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetToken returns the value of Token.
func (s *User) GetToken() string {
	return s.Token
}

// SetID sets the value of ID.
func (s *User) SetID(val uuid.UUID) {
	s.ID = val
}

// SetRole sets the value of Role.
func (s *User) SetRole(val Role) {
	s.Role = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *User) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetToken sets the value of Token.
func (s *User) SetToken(val string) {
	s.Token = val
}

func (*User) createUserRes()     {}
func (*User) getUserRes()        {}
func (*User) updateUserRoleRes() {}
